-------------------------
-- Italian Localization String resources
-- Miui Italy (www.miui.it)
------------------------
localization_Chinese_table = {
    calories_table={
        {str="≈1个茶叶蛋",	calories=96},
        {str="≈1片面包",	calories=100},
        {str="≈1瓶冰红茶",	calories=112},
        {str="≈1个煎蛋",	calories=118},
        {str="≈2串羊肉串",	calories=124},
        {str="≈1罐可乐",	calories=153},
        {str="≈3串羊肉串",	calories=186},
        {str="≈2个茶叶蛋",	calories=192},
        {str="≈2片面包",	calories=200},
        {str="≈1碗米饭",	calories=210},
        {str="≈1个馒头",	calories=221},
        {str="≈1根冰糖葫芦",	calories=223},
        {str="≈2瓶冰红茶",	calories=224},
        {str="≈1包小薯条",	calories=224},
        {str="≈1个蛋黄派",	calories=224},
        {str="≈2个煎蛋",	calories=236},
        {str="≈4串羊肉串",	calories=248},
        {str="≈1个汉堡",	calories=260},
        {str="≈1根油条",	calories=270},
        {str="≈1个肉包子",	calories=272},
        {str="≈3个茶叶蛋",	calories=288},
        {str="≈1个甜筒",	calories=290},
        {str="≈3片面包",	calories=300},
        {str="≈2罐可乐",	calories=306},
        {str="≈1包中薯条",	calories=328},
        {str="≈3个煎蛋",	calories=354},
        {str="≈1个蛋挞",	calories=375},
        {str="≈4片面包",	calories=400},
        {str="≈1包大薯条",	calories=402},
        {str="≈2碗米饭",	calories=420},
        {str="≈2个馒头",	calories=442},
        {str="≈2根冰糖葫芦",	calories=446},
        {str="≈1个蛋黄派",	calories=448},
        {str="≈1包方便面",	calories=470},
        {str="≈5片面包",	calories=500},
        {str="≈1盘蛋炒饭",	calories=516},
        {str="≈2个汉堡",	calories=520},
        {str="≈2根油条",	calories=540},
        {str="≈2个肉包子",	calories=544},
        {str="≈2个甜筒",	calories=580},
        {str="≈1碗方便面",	calories=581},
        {str="≈1碗牛肉拉面",	calories=593},
        {str="≈10串羊肉串",	calories=620},
        {str="≈3碗米饭",	calories=630},
        {str="≈3个馒头",	calories=663},
        {str="≈2个蛋挞",	calories=750},
        {str="≈3根油条",	calories=810},
        {str="≈3个肉包子",	calories=816},
    },

    ok='OK',

    hour='ore',
    minute='min',
    month='mese',
    day='giorno',
    step="passi",
    km='KM',
    minute_format='%d min',
    hour_minute_format='%d ore %d min',
    hour_format='%d ore',

    welcome_use="Benvenuto in MiBand",
    last_week_walked_format='La settimana scorsa hai fatto %d passi',
    last_week_walked_info_format='Hai camminato per %d Km, bruciando %d kcal',
    last_month_walked_format='Il mese scorso hai fatto %d passi',
    last_month_walked_info_format='Hai camminato per %d Km, bruciando %d kcal.',

    get_over_format=", circa %d grammi di grasso",
    click_to_get_help="Scopri cos\'altro fare con MiBand",
    take_a_walk="Fatti una passeggiata con MiBand.",
    take_a_walk_info="MiBand traccerà le tue abitudini per aiutarti a vivere meglio",
    unlock_hint="Sblocca il telefono con MiBand",
    unlock_hint_info="Un nuovo modo di sbloccare lo schermo",
    no_data_hint_0="Continua a muoverti, fai che lo sport sia parte della tua vita!",
    no_data_hint_1="Vuoi essere felice? Corri!",
    no_data_hint_2="L\'allenamento Cardio ti renderà scattante tutti i giorni!",
    no_data_hint_3="Solo il 15% - 20% del sonno di un adulto è sonno profondo",
    not_binded_hint="Non hai collegato alcun MiBand al tuo account, associalo ora",
    new_record_info="WOW! Hai appena migliorato il tuo record di camminata!",
    new_record_format="Nuovo record, %d passi, %s %d",
    today_goal_reached="Congratulazioni! Oggi hai raggiunto il tuo obiettivo",
    week_continue_reach_goal="Hai completato tutti gli obiettivi per un\'intera settimana! Che settimana fantastica!",
    challenge_format="Hai raggiunto i tuoi obiettivi per %d giorni!",
    personal_best_format="Il tuo record è %d giorni",
    active_time_format_0="%d ore",
    active_time_format_1="%d ore",
    active_time_format_2="%d ore %d min",
    activie_run_format_0="Hai corso %s. Bel lavoro!",
    activie_run_format_1="Hai corso %s. Fantastico!",
    activie_run_format_2="Hai corso %s, Che resistenza!",
    activie_run_consumed="Hai bruciato %d kcal. %s",

    get_distance_format=", per un totale di %d m",
    activity_walk_format="%s Hai camminato per %d passi %s",
    activity_walk_consumed_format="Bruciate %d kcal %s",

    activity_activity_format="%s Esercizio %s %s",
    last_night_sleeped_good_format="Questa notte hai dormito per %d ore %d min. Che dormita!",
    last_night_sleeped_normal_format="Questa notte hai dormito per %d ore %d min",
    deep_sleep_format="Il sonno profondo è durato %d ore %d min",

    battery_low_info="La batteria del MiBand è scarica",
    battery_very_low_info="Collega il MiBand all\'alimentazione elettrica",

    cannot_find_bracelet="Non riesci ad associare il tuo MiBand?",
    cannot_find_bracelet_info="Controlla che la batteria sia carica ed avvicinalo al telefono",

    challenge_to_get="%s giorni al nuovo record!",
    record_reach_max="Hai raggiunto il tuo record!",
    new_record_born="Nuovo record!",
}
