-------------------------
-- Italian Localization String resources
-- Miui Italy (www.miui.it)
------------------------
localization_Chinese_table = {
    calories_table={
        {str="≈ 2 uova sode",	calories=96},
        {str="≈ 1 fetta di pane",	calories=100},
        {str="≈ 1 bottiglia di tè freddo",	calories=112},
        {str="≈ 1 omelette",	calories=118},
        {str="≈ 2 fette di arrosto",	calories=124},
        {str="≈ 1 bibita in lattina",	calories=153},
        {str="≈ 3 fette di arrosto",	calories=186},
        {str="≈ 2 uova sode",	calories=192},
        {str="≈ 2 fette di pane",	calories=200},
        {str="≈ 1 ciotola di riso",	calories=210},
        {str="≈ 1 panino",	calories=221},
        {str="≈ 1 barbabietola",	calories=223},
        {str="≈ 2 bottiglie di tè freddo",	calories=224},
        {str="≈ 1 piccolo sacchetto di patatine",	calories=224},
        {str="≈ 1 fetta di torta",	calories=224},
        {str="≈ 2 omelette",	calories=236},
        {str="≈ 4 fette di arrosto",	calories=248},
        {str="≈ 1 hamburger",	calories=260},
        {str="≈ 1 frittella",	calories=270},
        {str="≈ 1 panino con carne",	calories=272},
        {str="≈ 3 uova sode",	calories=288},
        {str="≈ 1 gelato",	calories=290},
        {str="≈ 3 fette di pane",	calories=300},
        {str="≈ 2 bibite in lattina",	calories=306},
        {str="≈ 1 sacchetto di patatine",	calories=328},
        {str="≈ 3 omelette",	calories=354},
        {str="≈ 1 frittata",	calories=375},
        {str="≈ 4 fette di pane",	calories=400},
        {str="≈ 1 pacchetto grande di patatine",	calories=402},
        {str="≈ 2 ciotole di riso",	calories=420},
        {str="≈ 2 panini",	calories=442},
        {str="≈ 2 barbabietole",	calories=446},
        {str="≈ 1 torta",	calories=448},
        {str="≈ 1 porzione di noodles",	calories=470},
        {str="≈ 5 fette di pane",	calories=500},
        {str="≈ 1 piatto di rizo fritto",	calories=516},
        {str="≈ 2 hamburger",	calories=520},
        {str="≈ 2 frittelle",	calories=540},
        {str="≈ 2 panini di carne",	calories=544},
        {str="≈ 2 gelati",	calories=580},
        {str="≈ 1 porzione di noodles",	calories=581},
        {str="≈ 1 porzione di noodles al manzo",	calories=593},
        {str="≈ 10 fette di arrosto",	calories=620},
        {str="≈ 3 ciotole di riso",	calories=630},
        {str="≈ 3 panini",	calories=663},
        {str="≈ 2 frittate",	calories=750},
        {str="≈ 3 frittate",	calories=810},
        {str="≈3 panini con carne",	calories=816},
    },

    ok='OK',

    hour='ore',
    minute='min',
    month='mese',
    day='giorno',
    step="passi",
    km='KM',
    minute_format='%d min',
    hour_minute_format='%d ore %d min',
    hour_format='%d ore',

    welcome_use="Benvenuto in MiBand",
    last_week_walked_format='La settimana scorsa hai fatto %d passi',
    last_week_walked_info_format='Hai camminato per %d Km, bruciando %d kcal',
    last_month_walked_format='Il mese scorso hai fatto %d passi',
    last_month_walked_info_format='Hai camminato per %d Km, bruciando %d kcal.',

    get_over_format=", circa %d grammi di grasso",
    click_to_get_help="Scopri cos\'altro fare con MiBand",
    take_a_walk="Fatti una passeggiata con MiBand.",
    take_a_walk_info="MiBand traccerà le tue abitudini per aiutarti a vivere meglio",
    unlock_hint="Sblocca il telefono con MiBand",
    unlock_hint_info="Un nuovo modo di sbloccare lo schermo",
    no_data_hint_0="Continua a muoverti, fai che lo sport sia parte della tua vita!",
    no_data_hint_1="Vuoi essere felice? Corri!",
    no_data_hint_2="L\'allenamento Cardio ti renderà scattante tutti i giorni!",
    no_data_hint_3="Solo il 15% - 20% del sonno di un adulto è sonno profondo",
    not_binded_hint="Non hai collegato alcun MiBand al tuo account, associalo ora",
    new_record_info="WOW! Hai appena migliorato il tuo record di camminata!",
    new_record_format="Nuovo record, %d passi, %s %d",
    today_goal_reached="Congratulazioni! Oggi hai raggiunto il tuo obiettivo",
    week_continue_reach_goal="Hai completato tutti gli obiettivi per un\'intera settimana! Che settimana fantastica!",
    challenge_format="Hai raggiunto i tuoi obiettivi per %d giorni!",
    personal_best_format="Il tuo record è %d giorni",
    active_time_format_0="%d ore",
    active_time_format_1="%d ore",
    active_time_format_2="%d ore %d min",
    activie_run_format_0="Hai corso %s. Bel lavoro!",
    activie_run_format_1="Hai corso %s. Fantastico!",
    activie_run_format_2="Hai corso %s, Che resistenza!",
    activie_run_consumed="Hai bruciato %d kcal. %s",

    get_distance_format=", per un totale di %d m",
    activity_walk_format="%s Hai camminato per %d passi %s",
    activity_walk_consumed_format="Bruciate %d kcal %s",

    activity_activity_format="%s Esercizio %s %s",
    last_night_sleeped_good_format="Questa notte hai dormito per %d ore %d min. Che dormita!",
    last_night_sleeped_normal_format="Questa notte hai dormito per %d ore %d min",
    deep_sleep_format="Il sonno profondo è durato %d ore %d min",

    battery_low_info="La batteria del MiBand è scarica",
    battery_very_low_info="Collega il MiBand all\'alimentazione elettrica",

    cannot_find_bracelet="Non riesci ad associare il tuo MiBand?",
    cannot_find_bracelet_info="Controlla che la batteria sia carica ed avvicinalo al telefono",

    challenge_to_get="%s giorni al nuovo record!",
    record_reach_max="Hai raggiunto il tuo record!",
    new_record_born="Nuovo record!",

    --=================== Game =====================
    game_register="国庆七天日行万步, 赢取小米手机4",
    game_not_register_info="分享微博赢取微博大奖",
    game_register_info="已成功报名, 倒计时%s天",
    game_playing="国庆七天日行万步, 第%s天挑战中",
    game_playing_done="国庆七天日行万步, 第%s天达成",
    game_playing_lastday="最后一天即将完成日行万步挑战, 加油",
    game_playing_lastday_done="恭喜, 国庆七天日行万步挑战成功",
    game_playing_bonus_info="中将结果将在%s月%s日揭晓",
    click_to_show_result="点击查看活动进展",
    game_fail_title_ytd="很遗憾, 昨天未达成10000步",
    game_fail_title="很遗憾, %s月%s日未达成10000步",
    game_failed_title="国庆七天日行万步",
    game_fail_info="继续关注活动, 分享微博赢取微博大奖",

    game_bonus_hit="恭喜你成为“国庆七天日行万步”获奖者",
    game_bonus_hit_info="点击查看中奖结果",
    game_bonus_miss="国庆七天日行万步, 中奖结果已经揭晓",
    game_bonus_miss_info="快去看看哪些人中奖了吧",
    game_bonus_open="中奖结果将在%s月%s日揭晓, 敬请关注",
    game_bonus_open_tomorrow="中奖结果将在明天揭晓, 敬请关注",
    game_bonus_open_today="中奖结果将在今天揭晓, 敬请关注",


    share_to_content_for_event="“国庆七天日行万步得小米手机4”活动火热报名中，没有手环? 转发此微博即有机会赢取手环F码，点击链接查看活动详情。",
    game_share_to_registered="我报名参加了“日行万步得小米手机4”的活动，你愿意站在一旁默默祝福我还是一起来参加呢？离活动开始只剩%s天了, 快来报名吧",
    game_share_to_finished="今天10000步目标顺利完成",
    game_share_to_not_finished="向着10000步前进",
    game_share_to_failed="没想到呀，我居然挑战失败了",
    game_share_to_success="挑战成功！一共走了%s步",
    game_share_to_hit_bonus="一个不小心中奖了，快来围观给我点赞吧",
    game_share_to_not_hit_bonus="没有抽中，就当是给下次中奖攒人品了",
    less_than_one="小于1"
}
